# Generated by Django 4.1.3 on 2022-12-03 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0005_instruction1'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
                ('category', models.CharField(max_length=10)),
                ('description', models.TextField()),
                ('price', models.PositiveIntegerField()),
                ('weeks', models.PositiveIntegerField()),
                ('practical', models.PositiveIntegerField()),
            ],
        ),
    ]
